#!/usr/bin/env python3
# PYTHONIOENCODING=utf-8 — force UTF-8 output even on cp1252 terminals
"""
Engineering Pre-Mortem — Risk Scorer

Calculates risk scores using P × I × D (Probability × Impact × Detectability)
and produces a ranked, severity-tagged risk report.

Usage:
    python risk_scorer.py < input_risks.json
    python risk_scorer.py --risks-file risks.json
    python risk_scorer.py --interactive

Input format (JSON):
    {
      "risks": [
        {
          "id": "ARCH-001",
          "title": "Brief risk description",
          "probability": 4,
          "impact": 5,
          "detectability": 3,
          "category": "architecture",
          "description": "Detailed explanation of the risk"
        }
      ]
    }

Output: ranked markdown report to stdout.
"""

import json
import sys
from pathlib import Path

CRITICAL_THRESHOLD = 40
HIGH_THRESHOLD = 20
MEDIUM_THRESHOLD = 8

CATEGORY_WEIGHTS = {
    "architecture": 1.0,
    "runtime": 1.0,
    "security": 1.2,
    "scalability": 1.0,
    "ai_agent": 1.1,
    "integration": 1.0,
    "devops": 0.9,
    "human_process": 0.8,
}


def score_risk(risk: dict) -> dict:
    prob = int(risk.get("probability", 1))
    impact = int(risk.get("impact", 1))
    detect = int(risk.get("detectability", 1))
    category = risk.get("category", "architecture")
    weight = CATEGORY_WEIGHTS.get(category, 1.0)

    raw_score = prob * impact * detect
    weighted_score = round(raw_score * weight, 1)

    if weighted_score >= CRITICAL_THRESHOLD:
        severity = "CRITICAL"
    elif weighted_score >= HIGH_THRESHOLD:
        severity = "HIGH"
    elif weighted_score >= MEDIUM_THRESHOLD:
        severity = "MEDIUM"
    else:
        severity = "LOW"

    return {
        **risk,
        "probability": prob,
        "impact": impact,
        "detectability": detect,
        "raw_score": raw_score,
        "weighted_score": weighted_score,
        "severity": severity,
    }


def rank_risks(risks: list) -> list:
    scored = [score_risk(r) for r in risks]
    scored.sort(key=lambda x: x["weighted_score"], reverse=True)
    return scored


def format_report(risks: list) -> str:
    ranked = rank_risks(risks)
    lines = []

    lines.append("# Pre-Mortem Risk Assessment\n")

    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for r in ranked:
        severity_counts[r["severity"]] += 1

    lines.append("## Summary\n")
    lines.append(f"- **Critical**: {severity_counts['CRITICAL']}")
    lines.append(f"- **High**: {severity_counts['HIGH']}")
    lines.append(f"- **Medium**: {severity_counts['MEDIUM']}")
    lines.append(f"- **Low**: {severity_counts['LOW']}")
    lines.append(f"- **Total**: {len(ranked)}")
    lines.append("")

    lines.append("## Ranked Risks\n")
    for i, r in enumerate(ranked, 1):
        severity_tag = {
            "CRITICAL": "[CRITICAL]",
            "HIGH": "[HIGH]",
            "MEDIUM": "[MEDIUM]",
            "LOW": "[LOW]",
        }[r["severity"]]

        lines.append(f"### {i}. {r.get('id', f'RISK-{i:03d}')} — {severity_tag}")
        lines.append("")
        lines.append(f"**Title**: {r.get('title', 'Untitled risk')}")
        lines.append(f"**Category**: {r.get('category', 'uncategorized')}")
        lines.append(f"**Score**: {r['raw_score']} (P={r['probability']} x I={r['impact']} x D={r['detectability']})")
        if r['weighted_score'] != r['raw_score']:
            lines.append(f"**Weighted Score**: {r['weighted_score']} (category weight applied)")
        lines.append("")
        if r.get("description"):
            lines.append(r["description"])
            lines.append("")
        if r.get("warning_signals"):
            lines.append("**Early warning signals**:")
            for signal in r["warning_signals"]:
                lines.append(f"- {signal}")
            lines.append("")
        if r.get("mitigations"):
            lines.append("**Mitigations**:")
            for m in r["mitigations"]:
                lines.append(f"- {m}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by AnthraCanary risk_scorer.py | P x I x D scoring, threshold={CRITICAL_THRESHOLD}*")
    return "\n".join(lines)


def load_risks(source: str) -> list:
    try:
        data = json.loads(source)
    except json.JSONDecodeError:
        # Retry with utf-8 encoding (handles cp1252 / Windows encoding issues)
        try:
            data = json.loads(source.encode("utf-8").decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError, UnicodeEncodeError):
            raise
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        return data.get("risks", [])
    return []


def interactive_input() -> str:
    print("Risk Scorer — Interactive Mode", file=sys.stderr)
    print("Enter risk items one at a time. Type 'done' when finished.", file=sys.stderr)
    print(file=sys.stderr)

    risks = []
    idx = 1
    while True:
        print(f"--- Risk #{idx} ---", file=sys.stderr)
        title = input("  Title: ").strip()
        if not title or title.lower() == "done":
            break
        try:
            prob = int(input("  Probability (1-5): ").strip())
            impact = int(input("  Impact (1-5): ").strip())
            detect = int(input("  Detectability (1-5): ").strip())
        except ValueError:
            print("  [Invalid number, skipping]", file=sys.stderr)
            continue
        cat = input("  Category (architecture/runtime/security/scalability/ai_agent/integration/devops/human_process): ").strip()
        desc = input("  Description: ").strip()
        risks.append({
            "id": f"RISK-{idx:03d}",
            "title": title,
            "probability": prob,
            "impact": impact,
            "detectability": detect,
            "category": cat or "architecture",
            "description": desc,
        })
        idx += 1
        print(file=sys.stderr)

    return json.dumps({"risks": risks})


def main():
    if "--interactive" in sys.argv:
        source = interactive_input()
    elif "--risks-file" in sys.argv:
        idx = sys.argv.index("--risks-file") + 1
        if idx >= len(sys.argv):
            print("ERROR: --risks-file requires a path argument", file=sys.stderr)
            sys.exit(1)
        path = Path(sys.argv[idx])
        source = path.read_text(encoding="utf-8")
    else:
        source = sys.stdin.read()

    if not source.strip():
        print("ERROR: No input provided. Pipe JSON, use --risks-file, or --interactive.", file=sys.stderr)
        sys.exit(1)

    risks = load_risks(source)
    if not risks:
        print("ERROR: No valid risk items found in input.", file=sys.stderr)
        sys.exit(1)

    report = format_report(risks)
    # Safely print even on Windows cp1252 terminals
    try:
        print(report)
    except UnicodeEncodeError:
        # Fallback: replace unsupported characters
        safe = report.encode('utf-8', errors='replace').decode('utf-8', errors='replace')
        print(safe)


if __name__ == "__main__":
    main()
